- name: Start traefik
  ansible.builtin.command: "{{ docker_compose_bin }} up --detach"
  args:
    chdir: "{{ traefik_home }}"
  register: result
  changed_when: result.changed

- name: Restart traefik
  ansible.builtin.shell:
    "{{ docker_compose_bin }} down; {{ docker_compose_bin }} up --detach"
  args:
    chdir: "{{ traefik_home }}"
  register: result
  changed_when: result.changed
  ignore_errors: true
